controllers/RecadosController.php
<?
namespace app\controllers;

use app\Components\alertComponent;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\RecadosModel;
use Yii;

class RecadosController extends Controller {
    public function actionListarRecados(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $query = (new \yii\db\Query())
            ->select(
                'rec.id,
                rec.titulo,
                rec.conteudo,
                rec.dtInicio,
                rec.dtFim,
                rec.from_bloco,
                rec.from_condominio,
                blo.nomeB,
                cond.nomeCond'
            )
            ->from(RecadosModel::tableName().' rec')
            ->leftJoin(CondominiosModel::tableName().' cond', 'rec.from_condominio = cond.id')
            ->leftJoin(BlocosModel::tableName(). ' blo', 'rec.from_bloco = blo.id');

        $recados = $query->orderBy('rec.id')->all();          
        return $this->render('listar-recados', [
            'recados' => $recados,
        ]);
    }
    public function actionListarPorBloco(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = RecadosModel::find();
            $recados = $query->where(['from_bloco' => $request->get()])->all();
        }
        return $this->render('listar-por-bloco',[
            'list' => $recados
        ]);
        
    }

    public function actionCadastraRecado(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
           $redirSite = $request->get('redir');
        }
        return $this->render('cadastra-recado',['redirec' => $redirSite]);
    }

    public function actionRealizaCadastroRecado(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = new RecadosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['site/home']);
        }
        return $this->render('site/home');
    }

    public function actionRealizaCadastroRecadoBloco(){
        if(Yii::$app->user->isGuest){
           return $this->redirect(['site/login']);
       }
       $request = \yii::$app->request;
       if($request->isPost){
           $model = new RecadosModel();
           $model->attributes = $request->post();
           $model->save();
           return $this->redirect(['blocos/listar-blocos']);
       }
       return $this->render('blocos/listar-blocos');
   }

    public function actionEditaRecado(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = RecadosModel::find();
            $recados = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-recado',[
            'edit' => $recados
        ]);
    }
    public function actionRealizaEdicaoRecado(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = RecadosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if($model->update()){
                return $this->redirect(['site/home']);
            }else{
                alertComponent::myAlert('danger', "Não foi possivel editar");
            }
        }
        
    } 
    public function actionDeletaRecado(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isGet){
            $model = RecadosModel::findOne($request->get('id'));
            if($model->delete()){
                $redir = $request->get('redir');
                return $this->redirect([$redir,'myAlert' => ['type' =>'success', 'msg' =>'Registro deletado']]);
            }else{
                return $this->redirect([$redir, 'myAlert' => ['type' =>'danger', 'msg' =>'Registro não foi deletado']]);
            }
        }
    }
}
?>

views/recados/cadastra-recado.php
<?

use app\controllers\CondominiosController;
use yii\helpers\Url;

?>
<center>

    <h1>Cadastro de recado</h1>
</center>
<form action="<?=Url::to([($redirec == 'site/home')?'recados/realiza-cadastro-recado': 'realiza-cadastro-recado-bloco']);?>" method="post">
    <div class="row">
        <div class="col">
            <label for="titulo">Titulo do recado</label>
            <input type="text" class="form-control" name="titulo">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="conteudo">Conteúdo do recado</label>
            <textarea class="form-control" name="conteudo" required></textarea>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <label for="dtInicio">Data de inicio</label>
            <input type="date" class="form-control" name="dtInicio">
        </div>
        <div class="col-6">
            <label for="dtFim">Data do Fim</label>
            <input type="date" class="form-control" name="dtFim">
        </div>
    </div>
    <?if(!isset($_GET['from_bloco'])){?>
        <div class="row">
            <div class="col-sm-12 col-md-6">
            <label for="from_condominio">Selecione o Condominio</label><br>
                <select class="fromCondominio custom-select" name="from_condominio" >
                    <option value="">Selecione...</option>
                    <?foreach(CondominiosController::listarCondominiosSelect() as $condominio){?>
                        <option value="<?=$condominio['id']?>" ><?=$condominio['nomeCond']?></option>
                    <?}?>
                </select><br>
            </div>
            <div class="col-sm-12 col-md-6">
                <label for="from_bloco">Selecione o Bloco</label><br>
                <select class="fromBloco custom-select" name="from_bloco" >
                    <option value="">Selecione...</option>
                </select><br>
            </div>
        </div>
        
    <?}else{?>
        <input type="hidden" name="from_condominio" value="<?=$_GET['from_condominio']?>">
        <input type="hidden" name="from_bloco" value="<?=$_GET['from_bloco']?>">
    <?}?>
    <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn btn-dark mt-2 buttonEnviar"type="submit">Enviar</button>
</form>

views/recados/edita-recado.php
<?
use app\Components\selectedComponent;
use app\controllers\BlocosController;
use app\controllers\CondominiosController;
use yii\helpers\Url;

?>
<h1>Edita o recado</h1>
<form action="<?=Url::to(['recados/realiza-edicao-recado']);?>" method="post">
    <div class="row">
        <div class="col">
            <label for="titulo">Titulo do recado</label>
            <input type="text" class="form-control" name="titulo" value="<?=$edit['titulo']?>" required>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="conteudo">Conteúdo do recado</label>
            <textarea class="form-control" name="conteudo" required><?=$edit['conteudo']?></textarea>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <label for="dtInicio">Data de inicio</label>
            <input type="date" class="form-control" name="dtInicio" value="<?=$edit['dtInicio']?>" required>
        </div>
        <div class="col-6">
            <label for="dtFim">Data do Fim</label>
            <input type="date" class="form-control" name="dtFim" value="<?=$edit['dtFim']?>" required>
        </div>
    </div>
    <div class="row">
            <div class="col-sm-12 col-md-6">
            <label for="from_condominio">Selecione o Condominio</label><br>
                <select class="fromCondominio custom-select" name="from_condominio" >
                    <option value="">Selecione...</option>
                    <?foreach(CondominiosController::listarCondominiosSelect() as $condominio){?>
                        <option value="<?=$condominio['id']?>"  <?=selectedComponent::isSelected($condominio['id'],$edit['from_condominio']);?>><?=$condominio['nomeCond']?></option>
                    <?}?>
                </select><br>
            </div>
            <div class="col-sm-12 col-md-6">
                <label for="from_bloco">Selecione o Bloco</label><br>
                <select class="fromBloco custom-select" name="from_bloco" >
                    <option value="">Selecione...</option>
                    <?foreach(BlocosController::listarEditBlocosSelect($edit['from_condominio']) as $bloco){?>
                                <option value="<?=$bloco['id']?>" <?=selectedComponent::isSelected($bloco['id'],$edit['from_bloco']);?>><?=$bloco['nomeB']?></option>
                    <?}?>
                </select><br>
            </div>
    </div>
    <input type="hidden" name="id" value="<?=$edit['id']?>">
    <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn mt-2 btn-dark buttonEnviar"type="submit">Enviar</button>
</form>

views/recados/listar-por-bloco.php
<?
use yii\helpers\Url;

$url_site = Url::base(true);
?>

<center>
  <h3>Recados do Bloco</h3>
</center>
<div class="row">
  <?foreach($list as $dados){
    if( date('Y-m-d') <= $dados['dtFim']){
    ?>
  
  <div class="col-12 col-sm-6 col-md-4 ">
    <div class="card recados-bloco border-dark " >
      <div class="card-header bg-info">
        <div class="float-right">
            <button class="btn btn-outline-ligth btn-sm btnEdi edit text-dark"  data-id="<?=$dados['id']?>" id="editRecado"><i class="bi bi-pencil-square"></i></button>
            <a class="text-dark btn btn-outline-ligth btn-sm" id="delRecado" href="<?=$url_site?>/index.php?r=recados%2Fdeleta-recado&id=<?=$dados['id']?>&redir=blocos/listar-blocos"><i id="iconDel" class="bi bi-trash-fill"></i></a>
        </div>
      </div>
      <div class="card-body text-center" style="height: 220px;">
            <h5 class="card-title font-weight-bold border-bottom border-dark" id="titulo"><?=$dados['titulo']?></h5>
            <p class="card-text font-weight-normal" id="conteudo"><?=$dados['conteudo']?></p>
            <p class="font-weight-lighter" id="dtInicio">Inicio  <?=$dados['dtInicio']?>
            <p class="font-weight-lighter" id="dtFim">Fim  <?=$dados['dtFim']?></p>
            <p class="d-none" id="bloco"><?=$dados['from_bloco']?></p>
            <p class="d-none" id="cond"><?=$dados['from_condominio']?></p>
      </div>
    </div>
  </div>
   <?   
   }}?>
</div>

views/recados/listar-recados.php
<?
use app\Components\modalComponent;
use yii\helpers\Url;

$url_site = Url::base(true);
?>

  <?foreach($recados as $dados){?>
  
  <div class="mt-2 d-inline-block " >
    <div class="card card-recados border-dark " >
      <div class="card-header bg-info">
        <div class="float-right">
            <a class="openModal text-dark btn btn-outline-ligth btn-sm" href="<?=$url_site?>/index.php?r=recados%2Fedita-recado&id=<?=$dados['id']?>" ><i class="bi bi-pencil-square"></i></a>
            <a class="text-dark btn btn-outline-ligth btn-sm" id="delRecado" href="<?=$url_site?>/index.php?r=recados%2Fdeleta-recado&id=<?=$dados['id']?>&redir=site/home"><i id="iconDel" class="bi bi-trash-fill"></i></a>
        </div>
      </div>
      <div class="card-body card-recados-body text-center input-group-sm" >
          <div class="container justify-content-center">
            <h5 class="card-title font-weight-bold border-bottom border-dark" id="titulo"><?=$dados['titulo']?></h5>
          </div>
            <p class="card-text font-weight-normal" id="conteudo"><?=$dados['conteudo']?></p>
            <h7 class="card-title" id="bloco"><?=$dados['nomeB']?></h7>
            <h7 class="card-subtitle mb-2 text-muted" id="cond"><?=$dados['nomeCond']?></h7>
            <p class="font-weight-lighter" id="dtInicio">Inicio  <?=$dados['dtInicio']?>
            <p class="font-weight-lighter" id="dtFim">Fim  <?=$dados['dtFim']?></p>
      </div>
    </div>
  </div>
   <?}?>

<?=modalcomponent::modal();?>