controllers/CondominiosController.php
<?
namespace app\controllers;

use app\Components\alertComponent;
use app\Components\maskComponent;
use app\models\AdministradorasModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\CondominiosModel;
use app\models\ConselhoModel;
use Yii;

class CondominiosController extends Controller{
    public function actionListarCondominios(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $tabelaCond = CondominiosModel::tableName();
        $query = (new \yii\db\Query())
        ->select( 
            'cond.id,
            cond.nomeCond,
            cond.qtdBloco,
            cond.cep,
            cond.logradouro,
            cond.numero,
            cond.bairro,
            cond.cidade,
            cond.estado,
            cond.from_sindico,
            cond.dataCadastro,
            cons.nomeCons,
            adm.nomeAdm AS nome,
            cond.from_adm')
        ->from(CondominiosModel::tableName().' cond')
        ->leftJoin(ConselhoModel::tableName().' cons',' cond.from_sindico = cons.id')
        ->leftJoin (AdministradorasModel::tableName().' adm','  cond.from_adm = adm.id ');
        

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $condominios = $query->orderBy('nomeCond')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-condominios',[
            'condominios' => $condominios,
            'paginacao' => $paginacao,
        ]);
    }
    
    public static function listarCondominiosSelect(){
        $query = CondominiosModel::find();
        return $query->orderBy('nomeCond')->all();
    }

    public function actionCadastraCondominio(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        return $this->render('cadastra-condominio');
    }

    public function actionRealizaCadastroCondominio(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = new CondominiosModel();
            foreach ($request->post() as $ch => $value) {
                if($ch == 'cep'){
                    $arrayModel[$ch] = maskComponent::desmak($value);
                }else{
                    $arrayModel[$ch] = $value;
                }
            }
            $model->attributes = $arrayModel;
            $model->save();
            return $this->redirect(['condominios/listar-condominios']);
        }
        return $this->render('listar-condominios');
    }
    public function actionEditaCondominio(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = CondominiosModel::find();
            $condominio = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-condominio',[
            'edit' => $condominio
        ]);
    }
    public function actionRealizaEdicaoCondominio(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = CondominiosModel::findOne($request->post('id'));
            foreach ($request->post() as $ch => $value) {
                if($ch == 'cep'){
                    $arrayModel[$ch] = maskComponent::desmak($value);
                }else{
                    $arrayModel[$ch] = $value;
                }
            }
            $model->attributes = $arrayModel;
            
            if($model->update()){
                return $this->redirect(['condominios/listar-condominios']);
            }else{
                alertComponent::myAlert('danger', "Não foi possivel editar");
            }
        }
        
    } 
    public function actionDeletaCondominio(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isGet){
            $model = CondominiosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['condominios/listar-condominios','myAlert' => ['type' =>'success', 'msg' =>'Registro deletado']]);
            }else{
                return $this->redirect(['condominios/listar-condominios', 'myAlert' => ['type' =>'danger', 'msg' =>'Registro não foi deletado']]);
            }
        }
    }
}

?>

views/condominios/cadastra-condominio.php
<?

use app\Components\estadosComponent;
use app\controllers\AdministradorasController;
use yii\helpers\Url;
use app\controllers\CondominiosController;


?>
<center>
  <h3>Cadastrar Condominio</h3>
</center>
<form action="<?=Url::to(['condominios/realiza-cadastro-condominio']);?>" method="post" id="formCondominio">            
    <div class="form-group">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label for="nomeCond">Nome do condominio</label>
                <input type="text" name="nomeCond"  class="form-control" value="" required>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label for="qtdBloco">Quantidade de blocos</label>
                <input type="number" name="qtdBloco"  class="form-control" value="" required>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label for="cep">CEP</label>
                <input type="text" name="cep" class="form-control cep" value="" required>
                <a class="naoSeiCep" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Não sei meu CEP<i class="icofont-google-map"></i>
                </a>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label for="estado">Estado</label><br>
                <select name="estado" class="custom-select fromEstados">
                    <option value="">Selecione o Estado:</option>
                    <?foreach(estadosComponent::estados() as $sig=>$uf){?>
                        <option value="<?=$uf?>" data-uf="<?=$sig?>"><?=$uf?></option>
                    <?}?>
                </select><br>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12">
                <div class="collapse" id="collapseExample">
                    <div class="card bg-cep card-body">
                        <div class="row">
                            <div class="col-12 col-md-6 mb-3">
                                <label for="estado">Estado</label>
                                <select id="inputState" class="form-control fromEstados">
                                    <option value="">selecione...</option>
                                    <? foreach (estadosComponent::estados() as $sig => $uf) { ?>
                                        <option value="<?= $uf ?>" data-uf="<?= $sig ?>"><?= $uf ?></option>
                                    <? } ?>
                                </select>
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                <label for="cidade">Cidade</label>
                                <select id="inputState" class="form-control cidades">
                                    <option value="">Carregando...</option>
                                </select>
                            </div>
                            <div class="col-12 col-md-62 mb-12">
                                <label for="logradouroColapse">Logradouro</label>
                                <input type="text" class="form-control logradouroColapse" id="logradouroColapse"value="" placeholder="Logradouro">
                            </div>
                            <div class="col-12 col-md-62 mb-3">
                                <label for="inputState">CEP</label>
                                <select id="inputState" class="form-control cepColapse">
                                    <option value="">Carregando...</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="logradouro">Logradouro</label>
                <input type="text" name="logradouro" class="form-control logradouro viacep" value="" required>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="numero">Numero</label>
                <input type="text" name="numero" class="form-control viacep" value="">
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="bairro">Bairro</label>
                <input type="text" name="bairro" class="form-control bairro viacep" value="" required>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="cidade">Cidade</label>
                <input type="text" name="cidade" class="form-control cidades viacep" value="" required>        
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep"for="from_adm">Administradora</label><br>
                 <select name="from_adm"  class="custom-select viacep">
                     <option value="">Selecione a Administradora:</option>
                     <?foreach(AdministradorasController::listarAdministradorasSelect() as $administradora){?>
                         <option value="<?=$administradora['id']?>"><?=$administradora['nomeAdm']?></option>
                     <?}?>
                 </select><br>
            </div>
        </div>
    </div>
        <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn btn-dark buttonEnviar viacep"type="submit">Enviar</button>
</form>

views/condominios/edita-condominio.php
<?

use app\Components\estadosComponent;
use app\Components\maskComponent;
use app\Components\selectedComponent;
use app\controllers\AdministradorasController;
use yii\helpers\Url;



?>
<center>
  <h3>Editar Condominio</h3>
</center>
<form action="<?=Url::to(['condominios/realiza-edicao-condominio']);?>" method="post" id="formCondominio">            
    <div class="form-group">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label for="nomeCond">Nome do condominio</label>
                <input type="text" name="nomeCond" class="form-control" value="<?=$edit['nomeCond']?>" required>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label for="qtdBloco">Quantidade de blocos</label>
                <input type="number" name="qtdBloco" class="form-control" value="<?=$edit['qtdBloco']?>" required>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label for="cep">CEP</label>
                <input type="text" name="cep" class="form-control cep" value="<?=maskComponent::Mask($edit['cep'], 'cep')?>" required>
                <a class="naoSeiCep" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Não sei meu CEP<i class="icofont-google-map"></i>
                </a>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label for="estado">Estado</label><br>
                <select name="estado" class="custom-select fromEstados">
                    <option value="">Selecione o Estado:</option>
                    <?foreach(estadosComponent::estados() as $sig=>$uf){?>
                        <option class="fromEstados" value="<?=$uf?>"<?=selectedComponent::isSelected($uf, $edit['estado']);?>  data-uf="<?=$sig?>" ><?=$uf?></option></option>
                        <?}?>
                    </select><br>
            </div>
        </div>
        <!-- Collapse -->
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12">
                <div class="collapse" id="collapseExample">
                    <div class="card bg-cep card-body">
                        <div class="row">
                            <div class="col-12 col-md-6 mb-3">
                                <label for="estado">Estado</label>
                                <select id="inputState" class="form-control fromEstados">
                                    <option value="">selecione...</option>
                                    <? foreach (estadosComponent::estados() as $sig => $uf) { ?>
                                        <option value="<?= $uf ?>" data-uf="<?= $sig ?>"><?= $uf ?></option>
                                    <? } ?>
                                </select>
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                <label for="cidade">Cidade</label>
                                <select id="inputState" class="form-control cidades">
                                    <option value="">Carregando...</option>
                                </select>
                            </div>
                            <div class="col-12 col-md-62 mb-12">
                                <label for="logradouroColapse">Logradouro</label>
                                <input type="text" class="form-control logradouroColapse" id="logradouroColapse"value="" placeholder="Logradouro">
                            </div>
                            <div class="col-12 col-md-62 mb-3">
                                <label for="inputState">CEP</label>
                                <select id="inputState" class="form-control cepColapse">
                                    <option value="">Carregando...</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="logradouro">Logradouro</label>
                <input type="text" name="logradouro" class="form-control logradouro viacep" value="<?=$edit['logradouro']?>" required>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="numero">Numero</label>
                <input type="text" name="numero" class="form-control viacep" value="<?=$edit['numero']?>">
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="bairro">Bairro</label>
                <input type="text" name="bairro" class="form-control bairro viacep" value="<?=$edit['bairro']?>" required>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="cidade">Cidade</label>
                <input type="text" name="cidade" class="form-control cidades viacep" value="<?=$edit['cidade']?>" required>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <label class="viacep" for="from_adm">Administradora</label><br>
                <select name="from_adm"  class="custom-select viacep">
                    <option value="">Selecione a Administradora:</option>
                    <?foreach(AdministradorasController::listarAdministradorasSelect() as $administradora){?>
                        <option value="<?=$administradora['id']?>"  <?=selectedComponent::isSelected($administradora['id'],$edit['from_adm']);?>><?=$administradora['nomeAdm']?></option>
                    <?}?>
                </select><br>
            </div>
        </div>
    </div>
        <input type="hidden" name="id" value="<?=$edit['id']?>">
        <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn btn-dark buttonEnviar viacep"type="submit">Enviar</button>
</form>

views/condominios/listar-condominios.php
<?

use app\Components\alertComponent;
use app\Components\maskComponent;
use app\Components\modalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$url_site = Url::base(true);
if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'], $_GET['myAlert']['msg']);
}
?>

<div class="container m-3 listTable">
    <table class="table   table-responsive table-responsive-sm table-responsive-md table-responsive-lg table-responsive-xl " border="1" id="listaCondominio">
        <thead class="thead-dark">
            <tr>
                <th scope="col" colspan="12"><a href="<?=$url_site?>/index.php?r=condominios%2Fcadastra-condominio" class="text-dark openModal btn btn-light" >Adicionar</a></th>
            </tr>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Administradora</th>
                <th scope="col">Quantidade de bloco</th>
                <th scope="col">CEP</th>
                <th scope="col">Logradouro</th>
                <th scope="col">Dt Cadastro</th>
                <th scope="col" colspan="2"></th>
            </tr>
        </thead>
        <tbody>
            <?foreach($condominios as $dados){?>
                <tr data-id="<?=$dados['id']?>">
                    <td><?= $dados['nomeCond'] ?></td>
                    <td><?= $dados['nome'] ?></td>
                    <td><?= $dados['qtdBloco'] ?></td>
                    <td><?= maskComponent::Mask($dados['cep'],'cep') ?></td>
                    <td><?=$dados['logradouro']?>,<?= $dados['numero'] ?> - <?= $dados['bairro'] ?> - <?= $dados['cidade'] ?> - <?= $dados['estado'] ?></td>
                    <td><?=yii::$app->formatter->format($dados['dataCadastro'],'date') ?></td>
                    <td><a href="<?=$url_site?>/index.php?r=condominios%2Fedita-condominio&id=<?=$dados['id']?>" class="openModal btn btn-dark text-white"><i class="bi bi-pencil-square"></i></a></td>
                    <td><a href="<?=$url_site?>/index.php?r=condominios%2Fdeleta-condominio&id=<?=$dados['id']?>" class="removerCondominio btn btn-dark text-white"><i class="bi bi-trash-fill"></i></a></td>
                </tr>
            <?} ?>
        </tbody>
    </table>
    <div class="container">
        <div class="row">
            <?= LinkPager::widget(
                [
                    'pagination' => $paginacao, 
                    'linkContainerOptions' => [
                        'class' => 'page-item'
                        ]
                    , 'linkOptions' => [
                        'class' => 'page-link'
                    ],
                    'disabledListItemSubTagOptions' => [
                        'class' => 'page-link'
                    ]
                ]
                ) ?>
            <div class="totalRegistros col-sm-6"><h5>Total Registros<span class="badge"><?=$paginacao->totalCount?></span> </h5></div>
        </div>
    </div>
</div>
    <?=modalComponent::modal()?>