controllers/BlocosController.php
<?
namespace app\controllers;

use app\Components\alertComponent;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use Yii;

class BlocosController extends Controller{
    public function actionListarBlocos(){
            if(Yii::$app->user->isGuest){
                return $this->redirect(['site/login']);
            }

        $query =  (new \yii\db\Query())
            ->select(
            'blo.id,
            blo.nomeB,
            blo.andares,
            blo.qtdUnid,
            blo.dataCadastro,
            cond.nomeCond,
            blo.from_condominio')
            ->from(BlocosModel::tableName().' blo')
            ->leftJoin(CondominiosModel::tableName().' cond','blo.from_condominio = cond.id');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $blocos = $query->orderBy('cond.nomeCond')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();
        return $this->render('listar-blocos',[
            'blocos' => $blocos,
            'paginacao' => $paginacao,
        ]);
    }

    public static function listarBlocosSelect(){
        $query = BlocosModel::find();
        return $query->orderBy('nomeB')->all();
    }

    public static function listarEditBlocosSelect($from){
        $query = BlocosModel::find();
        $data = $query->where(['from_condominio' => $from])->orderBy('nomeB')->all();
        return $data;
    }

    public function actionListarBlocosApi(){
            if(Yii::$app->user->isGuest){
                return $this->redirect(['site/login']);
            }
        $request = \yii::$app->request;
        $query = BlocosModel::find();
        $data = $query->where(['from_condominio' => $request->post()])->orderBy('nomeB')->all();
        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nomeB'] = $d['nomeB'];
            $i++;
        }
        return json_encode($dados);
    }
    
    public function actionCadastraBloco(){
            if(Yii::$app->user->isGuest){
                return $this->redirect(['site/login']);
            }
        $this->layout = false;
        return $this->render('cadastra-bloco');
    }
    
    public function actionRealizaCadastroBloco(){
            if(Yii::$app->user->isGuest){
                return $this->redirect(['site/login']);
            }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/listar-blocos']);
        }
        return $this->render('listar-blocos');
    }
    public function actionEditaBloco(){
            if(Yii::$app->user->isGuest){
                return $this->redirect(['site/login']);
            }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocosModel::find();
            $bloco = $query->where(['id'=> $request->get()])->one();
        }
        return $this->render('edita-bloco',[
            'edit' => $bloco
        ]);
    }
    public function actionRealizaEdicaoBloco(){
            if(Yii::$app->user->isGuest){
                return $this->redirect(['site/login']);
            }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = BlocosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if($model->update()){
                return $this->redirect(['blocos/listar-blocos']);
            }else{
                alertComponent::myAlert('danger', "Não foi possivel editar");
            }
        }
        
    } 
    public function actionDeletaBloco(){
            if(Yii::$app->user->isGuest){
                return $this->redirect(['site/login']);
            }
        $request = \yii::$app->request;
        if($request->isGet){
            $model = BlocosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['blocos/listar-blocos','myAlert' => ['type' =>'success', 'msg' =>'Registro deletado']]);
            }else{
                return $this->redirect(['blocos/listar-blocos', 'myAlert' => ['type' =>'danger', 'msg' =>'Registro não foi deletado']]);
            }
        }
    }
}
?>

views/blocos/cadastra-bloco.php
<?
use yii\helpers\Url;
use app\controllers\CondominiosController;
?>
<center>
  <h3>cadastrar Bloco</h3>
</center>
<form action="<?=Url::to(['blocos/realiza-cadastro-bloco']);?>" method="post" id="formBloco">            
    <div class="form-group">
        <label for="nomeB">Nome do bloco</label>
        <input type="text" name="nomeB" class="form-control"  value="" required>
        <label for="andares">Quantidade de andares</label>
        <input type="number" name="andares" class="form-control" value="" required>
        <label for="qtdUnid">Quantidade de unidades</label>
        <input type="number" name="qtdUnid" class="form-control" value="" required>
        <label for="from_condominio">Condominio</label><br>
        <select name="from_condominio" class="custom-select" >
            <option value="">Selecione o Condominio</option>
            <?foreach(CondominiosController::listarCondominiosSelect() as $condominio){?>
                <option value="<?=$condominio['id']?>" ><?=$condominio['nomeCond']?></option>
            <?}?>
        </select><br>
    </div>
        <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn btn-dark buttonEnviar"type="submit">Enviar</button>
</form>

views/blocos/edita-bloco.php
<?

use app\Components\selectedComponent;
use yii\helpers\Url;
use app\controllers\CondominiosController;
?>
<center>
  <h3>Edita Bloco</h3>
</center>
<form action="<?=Url::to(['blocos/realiza-edicao-bloco']);?>" method="post" id="formBloco">            
    <div class="form-group">
        <label for="nomeB">Nome do bloco</label>
        <input type="text" name="nomeB" class="form-control"  value="<?=$edit['nomeB']?>" required>
        <label for="andares">Quantidade de andares</label>
        <input type="number" name="andares" class="form-control" value="<?=$edit['andares']?>" required>
        <label for="qtdUnid">Quantidade de unidades</label>
        <input type="number" name="qtdUnid" class="form-control" value="<?=$edit['qtdUnid']?>" required>
        <label for="from_condominio">Condominio</label><br>
        <select class="fromCondominio custom-select" name="from_condominio" >
            <option value="">Selecione o Condominio</option>
            <?foreach(CondominiosController::listarCondominiosSelect() as $condominio){?>
                <option value="<?=$condominio['id']?>"  <?=selectedComponent::isSelected($condominio['id'],$edit['from_condominio']);?>><?=$condominio['nomeCond']?></option>
            <?}?>
        </select><br>
    </div>
        <input type="hidden" name="id" value="<?=$edit['id']?>">
        <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn btn-dark buttonEnviar"type="submit">Enviar</button>
</form>

views/blocos/listar-blocos.php
<?

use app\Components\alertComponent;
use app\Components\modalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$url_site = Url::base(true);
if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'], $_GET['myAlert']['msg']);
}
?>
<div class="container m-3 listTable">
    <table class="table table-hover table-responsive-sm table-responsive-md table-responsive-lg" border="1" id="listaBloco">
        <thead class="thead-dark">
            <tr>
                <th scope="col" colspan="9"><a href="<?=$url_site?>/index.php?r=blocos%2Fcadastra-bloco" class="btn btn-light text-dark openModal" >Adicionar</a></th>
            </tr>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Condominio</th>
                <th scope="col">Quantidade de andares</th>
                <th scope="col">Quantidade de unidades</th>
                <th scope="col">Dt de Cadastro</th>
                <th scope="col" colspan="2">Recados</th>
                <th scope="col" colspan="2"></th>
            </tr>
        </thead>
        <tbody>
            <?foreach($blocos as $dados){?>
                <tr data-id="<?=$dados['id']?>">
                    <td><?= $dados['nomeB'] ?></td>
                    <td><?= $dados['nomeCond'] ?></td>
                    <td><?= $dados['andares'] ?></td>
                    <td><?= $dados['qtdUnid'] ?></td>
                    <td><?=yii::$app->formatter->format($dados['dataCadastro'],'date') ?></td>
                    <td><a href="<?=$url_site?>/index.php?r=recados%2Flistar-por-bloco&from_bloco=<?=$dados['id']?>" class="openModal btn btn-dark text-white"><i class="bi bi-chat-square-text-fill"></i></a></td>
                    <td><a href="<?=$url_site?>/index.php?r=recados%2Fcadastra-recado&from_bloco=<?=$dados['id']?>&from_condominio=<?=$dados['from_condominio']?>&redir=blocos/listar-blocos" class="openModal btn btn-dark text-white"><i class="bi bi-plus-circle-dotted"></i></a></td>
                    <td><a href="<?=$url_site?>/index.php?r=blocos%2Fedita-bloco&id=<?=$dados['id']?>" class="openModal btn btn-dark text-white"><i class="bi bi-pencil-square"></i></a></td>
                    <td><a href="<?=$url_site?>/index.php?r=blocos%2Fdeleta-bloco&id=<?=$dados['id']?>" class="removerbloco btn btn-dark text-white"><i class="bi bi-trash-fill"></i></a></td>
                </tr>
            <?} ?>
        </tbody>
    </table>
    <div class="container">
        <div class="row">
            <?= LinkPager::widget(
                [
                    'pagination' => $paginacao, 
                    'linkContainerOptions' => [
                        'class' => 'page-item'
                        ]
                    , 'linkOptions' => [
                        'class' => 'page-link'
                    ],
                    'disabledListItemSubTagOptions' => [
                        'class' => 'page-link'
                    ]
                ]
                ) ?>
           <div class="totalRegistros col-sm-6"><h5>Total Registros<span class="badge"><?=$paginacao->totalCount?></span> </h5></div>
        </div>
    </div>
</div>
    <?=modalComponent::modal();?>