controllers/AdministradorasController.php
<?
namespace app\controllers;

use app\Components\alertComponent;
use app\Components\maskComponent;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\AdministradorasModel;
use Yii;

class AdministradorasController extends Controller {
    public function actionListarAdministradoras(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
       
        $query = AdministradorasModel::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $administradoras = $query->orderBy('nomeAdm')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-administradoras', [
            'administradoras' => $administradoras,
            'paginacao' => $paginacao,
        ]);
    }

    public static function listarAdministradorasSelect(){
        $query = AdministradorasModel::find();

        return $query->orderBy('nomeAdm')->all();
    }

    public function actionCadastraAdministradora(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        return $this->render('cadastra-administradora');
    }

    public function actionRealizaCadastroAdministradora(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = new AdministradorasModel();
            foreach ($request->post() as $ch => $value) {
                if($ch == 'cnpj'){
                    $arrayModel[$ch] = maskComponent::desmak($value);
                }else{
                    $arrayModel[$ch] = $value;
                }
            }
            $model->attributes = $arrayModel;
            $model->save();
            return $this->redirect(['administradoras/listar-administradoras']);
        }
        return $this->render('cadastra-administradora');
    }
    public function actionEditaAdministradora(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = AdministradorasModel::find();
            $administradora = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-administradora',[
            'edit' => $administradora
        ]);
    }
    public function actionRealizaEdicaoAdministradora(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isPost){
            $model = AdministradorasModel::findOne($request->post('id'));
            foreach ($request->post() as $ch => $value) {
                if($ch == 'cnpj'){
                    $arrayModel[$ch] = maskComponent::desmak($value);
                }else{
                    $arrayModel[$ch] = $value;
                }
            }
            $model->attributes = $arrayModel;            
            if($model->update()){
                return $this->redirect(['administradoras/listar-administradoras']);
            }else{
                alertComponent::myAlert('danger', "Não foi possivel editar");
            }
        }
        
    } 
    public function actionDeletaAdministradora(){
         if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;
        if($request->isGet){
            $model = AdministradorasModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['administradoras/listar-administradoras','myAlert' => ['type' =>'success', 'msg' =>'Registro deletado']]);
            }else{
                return $this->redirect(['administradoras/listar-administradoras', 'myAlert' => ['type' =>'danger', 'msg' =>'Registro não foi deletado']]);
            }
        }
    }
}
?>

views/administradoras/cadastra-administradora.php
<?
use yii\helpers\Url;
?>
<center>
  <h3>Cadastrar Administradora</h3>
</center>
<form method="post" id="formadm" action="<?=Url::to(['administradoras/realiza-cadastro-administradora']);?>">            
    <div class="form-group">
        <label for="nomeAdm">Nome</label>
        <input type="text" name="nomeAdm" class="form-control" value="" required>        
        <label for="cnpj">CNPJ</label>
        <input type="text" name="cnpj" class="form-control" value="" required>
    </div>
        <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn btn-dark buttonEnviar"type="submit">Enviar</button>
</form>

views/administradoras/edita-administradora.php
<?

use app\Components\maskComponent;
use yii\helpers\Url;
?>
<center>
  <h3>Editar administradora</h3>
</center>
<form method="post" id="formadm" action="<?=Url::to(['administradoras/realiza-edicao-administradora']);?>">            
    <div class="form-group">
        <label for="nomeAdm">Nome</label>
        <input type="text" name="nomeAdm" class="form-control" value="<?=$edit['nomeAdm']?>" required>        
        <label for="cnpj">CNPJ</label>
        <input type="text" name="cnpj" class="form-control" value="<?=maskComponent::Mask($edit['cnpj'], 'cnpj')?>" required>
        
    </div>
        <input type="hidden" name="id" value="<?=$edit['id']?>">
        <input type="hidden" name="<?=\yii::$app->request->csrfParam;?>" value="<?=\yii::$app->request->csrfToken;?>">
    <button class="btn btn-dark buttonEnviar"type="submit">Enviar</button>
</form>

views/administradoras/listar-administradoras.php
<?

use app\Components\alertComponent;
use app\Components\maskComponent;
use app\Components\modalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$url_site = Url::base(true);
if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'], $_GET['myAlert']['msg']);
}
?>
<div class="container m-3 listTable">
        <table class="table table-hover table-responsive-sm table-responsive-md table-responsive-lg" border="1" id="listaAdm">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" colspan="5"><a href="<?=$url_site?>/index.php?r=administradoras%2Fcadastra-administradora" class="btn btn-light text-dark openModal" >Adicionar</a></th>
                </tr>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">CNPJ</th>
                    <th scope="col">Dt de Cadastro</th>
                    <th scope="col" colspan="2"></th>
                </tr>
    <? foreach ($administradoras as $dados) {?>
        <tbody>
            <tr data-id="<?=$dados['id']?>">
                <td><?= $dados['nomeAdm'] ?></td>
                <td><?= maskComponent::Mask($dados['cnpj'],'cnpj') ?></td>
                <td><?=yii::$app->formatter->format($dados['dataCadastro'],'date') ?></td>
                <td><a href="<?=$url_site?>/index.php?r=administradoras%2Fedita-administradora&id=<?=$dados['id']?>" class="btn btn-dark  openModal text-white"><i class="bi bi-pencil-square"></i></a></td>
                <td><a href="<?=$url_site?>/index.php?r=administradoras%2Fdeleta-administradora&id=<?=$dados['id']?>" class="removerCliente text-white btn btn-dark"><i class="bi bi-trash-fill"></i></a></td>
                
            </tr>
            <? } ?>
        </tbody>
        
    </table>
    <div class="container ">
        <div class="row">
            <?= LinkPager::widget(
                [
                    'pagination' => $paginacao, 
                    'linkContainerOptions' => [
                        'class' => 'page-item'
                        ]
                    , 'linkOptions' => [
                        'class' => 'page-link'
                    ],
                    'disabledListItemSubTagOptions' => [
                        'class' => 'page-link'
                    ]
                ]
                ) ?>
            <div class="totalRegistros col-sm-6"><h5>Total Registros<span class="badge"><?=$paginacao->totalCount?></span> </h5></div>
        </div>
    </div>
</div>
    <?=modalComponent::modal()?>